-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 16:22:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookclub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookclub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookclub` DEFAULT CHARACTER SET utf8 ;
-- USE `bookclub` ;

-- -----------------------------------------------------
-- Table `bookclub`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookclub`.`members` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(15) NULL,
  `last_name` VARCHAR(25) NULL,
  `address` VARCHAR(50) NULL,
  `phonenumber` VARCHAR(15) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookclub`.`credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookclub`.`credentials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `members_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_credentials_members_idx` (`members_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_credentials_members`
    FOREIGN KEY (`members_id`)
    REFERENCES `bookclub`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookclub`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookclub`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `author` VARCHAR(45) NULL,
  `bookcover` VARCHAR(64) NULL,
  `status` VARCHAR(45) NULL,
  `members_id` INT(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_books_members1_idx` (`members_id` ASC),
  CONSTRAINT `fk_books_members1`
    FOREIGN KEY (`members_id`)
    REFERENCES `bookclub`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookclub`.`borrow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookclub`.`borrow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `members_id` INT NOT NULL,
  `books_id` INT NOT NULL,
  `borrow_date` DATETIME NULL,
  `return_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_borrow_members1_idx` (`members_id` ASC),
  INDEX `fk_borrow_books1_idx` (`books_id` ASC),
  CONSTRAINT `fk_borrow_members1`
    FOREIGN KEY (`members_id`)
    REFERENCES `bookclub`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_borrow_books1`
    FOREIGN KEY (`books_id`)
    REFERENCES `bookclub`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
